name: Build and Test

on:
  push:
    branches: [ javadocbackend ]   # change to master if needed
  workflow_dispatch:

permissions:
  contents: write        # needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test backend
        working-directory: backend
        run: mvn -B -ntp -fae verify

      - name: Build & test frontend
        working-directory: frontend
        run: mvn -B -ntp -fae verify