name: Build & Publish Javadoc

on:
  push:
    branches: [ main ]     # change to master if needed
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... other steps

      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs