name: Build and Test

on:
  push:
    branches: [ IntergratedBuild ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 1) Build and INSTALL backend
      - name: Build & install backend
        working-directory: backend
        run: mvn install

      # 2) Build Frontend and run tests
      - name: Build & test frontend
        working-directory: frontend
        run: mvn verify
